name             'thecollegesound'
maintainer       'The College Sound'
maintainer_email 'admin@thecollegesound.com'
license          'All rights reserved'
description      'Installs/Configures The College Sound web server'
version          '0.1.0'

depends 'application'
depends 'application_python'
depends 'nginx'
depends 'mysql'
depends 'gunicorn'
